name: Deploy to Render

on:
  push:
    branches:
      - main
  pull_request:
    branches: [ main ]
    types: [ opened, synchronize ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: curl ${{ secrets.RENDER_DEPLOY_HOOK }}
        if: ${{ github.event_name == 'push' }}
