name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [ main ]
    types: [ opened, synchronize ]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: "24"
      - run: npm install
      - run: npm run eslint
      - run: npm run test
      - run: npm run build

  e2e_test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

  deploy:
    runs-on: ubuntu-latest
    if: ${{ success() && github.event_name == 'push' }}
    steps:
      - run: curl ${{ secrets.RENDER_DEPLOY_HOOK }}

  tag_release:
    needs: [ simple_deployment_pipeline, e2e_test ]
    runs-on: ubuntu-latest
    env:
      COMMIT_MESSAGES:  ${{ join(github.event.commits.*.message, ' ')}}
    if: ${{ github.event_name == 'push' && !contains('#skip', '${COMMIT_MESSAGES}') }}
    steps:
      - run: |
          echo ${{ !contains('#skip', '${COMMIT_MESSAGES}') }}
          echo '${COMMIT_MESAGES}'
      - uses: actions/checkout@v5
        with:
          fetch-depth: "0"

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.75.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
